export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING'

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const ACTIVATE = 'ACTIVATE';
export const USERS = 'USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const COLLECTORS = 'COLLECTORS';
export const USER_STREETS = 'USER_STREETS';

export const SCHEDULES = 'SCHEDULES';
export const SCHEDULE = 'SCHEDULE';
export const CREATE_SCHEDULE = 'CREATE_SCHEDULE';
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
export const FETCH_BY_SEARCH_SCHEDULES = 'FETCH_BY_SEARCH_SCHEDULES'

export const BARANGAYS = 'BARANGAYS';

export const ANNOUNCEMENTS = 'ANNOUNCEMENTS';
export const CREATE_ANNOUNCEMENT = 'CREATE_ANNOUNCEMENT';
export const UPDATE_ANNOUNCEMENT = 'UPDATE_ANNOUNCEMENT';
export const DELETE_ANNOUNCEMENT = 'DELETE_ANNOUNCEMENT';
export const FETCH_BY_SEARCH_ANNOUNCEMENT = 'FETCH_BY_SEARCH_ANNOUNCEMENT';

export const MESSAGE = 'MESSAGE';
export const MESSAGE_TYPE ='MESSAGE_TYPE';

export const BIO_COUNT_TODAY = 'BIO_COUNT_TODAY';
export const NON_BIO_COUNT_TODAY = 'NON_BIO_COUNT_TODAY';
export const RECYCLABLE_COUNT_TODAY = 'RECYCLABLE_COUNT_TODAY';

export const COLLECTIONS = 'COLLECTIONS';
export const TOTAL_COLLECTED = 'TOTAL_COLLECTED';

export const BIODEGRADABLE_DYNAMIC = 'BIODEGRADABLE_DYNAMIC';
export const BIO_COUNT_MONTH = 'BIO_COUNT_MONTH';
export const BIO_COUNT_YEAR = 'BIO_COUNT_YEAR';
export const BIO_SORTED = 'BIO_SORTED';

export const NON_BIODEGRADABLE_DYNAMIC = 'NON_BIODEGRADABLE_DYNAMIC';
export const NON_BIO_COUNT_MONTH = 'NON_BIO_COUNT_MONTH';
export const NON_BIO_COUNT_YEAR = 'NON_BIO_COUNT_YEAR';
export const NON_BIO_SORTED = 'NON_BIO_SORTED';

export const RECYCLABLE_DYNAMIC = 'RECYCLABLE_DYNAMIC';
export const RECYCLABLE_COUNT_MONTH = 'RECYCLABLE_COUNT_MONTH';
export const RECYCLABLE_COUNT_YEAR = 'RECYCLABLE_COUNT_YEAR';
export const RECYCLABLE_SORTED = 'RECYCLABLE_SORTED';

export const COLLECTED_COUNT_TODAY = 'COLLECTED_COUNT_TODAY'
export const COLLECTED_COUNT_MONTH = 'COLLECTD_COUNT_MONTH'
export const COLLECTED_COUNT_YEAR = 'COLLECTED_COUNT_YEAR'
export const COLLECTED_SORTED = 'COLLECTED_SORTED'
export const COLLECTED_WASTE_TYPE = 'COLLECTED_WASTE_TYPE'