export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING'

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const ACTIVATE = 'ACTIVATE';
export const USERS = 'USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const COLLECTORS = 'COLLECTORS';

export const SCHEDULES = 'SCHEDULES';
export const SCHEDULE = 'SCHEDULE';
export const CREATE_SCHEDULE = 'CREATE_SCHEDULE';
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
export const FETCH_BY_SEARCH_SCHEDULES = 'FETCH_BY_SEARCH_SCHEDULES'

export const BARANGAYS = 'BARANGAYS';

export const ANNOUNCEMENTS = 'ANNOUNCEMENTS';
export const CREATE_ANNOUNCEMENT = 'CREATE_ANNOUNCEMENT';
export const UPDATE_ANNOUNCEMENT = 'UPDATE_ANNOUNCEMENT';
export const DELETE_ANNOUNCEMENT = 'DELETE_ANNOUNCEMENT';
export const FETCH_BY_SEARCH_ANNOUNCEMENT = 'FETCH_BY_SEARCH_ANNOUNCEMENT';

export const MESSAGE = 'MESSAGE';
export const MESSAGE_TYPE ='MESSAGE_TYPE';

export const BIO_COUNT = 'BIO_COUNT';
export const NON_BIO_COUNT = 'NON_BIO_COUNT';
export const RECYCLABLE_COUNT = 'RECYCLABLE_COUNT';

